config/routes.rb
Rails.application.routes.draw do

  resources :subsystem_tags
  namespace :initiatives do
    resources :imports, only: [:new, :create, :update]
  end

  resources :checklist_items, only: [:show, :edit, :update]

  namespace :organisations do
    resources :imports, only: [:new, :create, :update]
  end

  namespace :transition_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, skip: [:registrations], :controllers => { :invitations => 'invitations' }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :communities
  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics, only: [:show],
      controller: 'sustainable_development_goal_alignment_cards',
      action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared, constraints: {
    id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
  }, only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show],
      controller: 'shared',
      action: 'characteristic'
  end

  resources :stakeholder_types
  resources :users do
    post :stop_impersonating, on: :collection

    member do
      get 'remove_from_account'
    end
  end

  resources :video_tutorials
  resource :welcome_message, only: [:show]
  resources :wicked_problems

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
    end
  end

  resources :search_results, only: [:index, :show]

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'

  namespace :system do
    resources :stakeholder_types
    resources :users do
      post :impersonate, on: :member

      member do
        get 'undelete'
        get 'resend_invitation'
      end
    end
  end

  root to: "home#index"
end

app/models/initiatives.rb
module Initiatives
  def self.table_name_prefix
    'initiatives_'
  end
end

app/controllers/initiatives/imports_controller.rb
class Initiatives::ImportsController < ApplicationController
  before_action :require_account_selected, only: [:new, :create, :edit, :update]
  before_action :set_initiatives_import, only: [:show, :edit, :update, :destroy]

  def new
    @initiatives_import = current_account.initiatives_imports.build(
      card_type: scorecard_type_from_scope(params[:scope])
    )
    authorize @initiatives_import
  end

  def create
    @initiatives_import = current_account.initiatives_imports.build(
      initiatives_import_params.merge(user: current_user)
    )
    authorize @initiatives_import

    if @initiatives_import.save && @initiatives_import.process(current_account)
      redirect_to initiatives_path, notice: 'Initiative records successfully imported.'
    else
      render :new
    end

    @initiatives_import.destroy
    file_system = Shrine.storages[:cache]
    file_system.clear! { |path| path.mtime < Time.now - 1.hour }
  end

  def update
    if @initiatives_import.update(initiatives_import_params)
      redirect_to @initiatives_import, notice: 'Import was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_initiatives_import
    @initiatives_import = Initiatives::Import.find(params[:id])
    authorize @initiatives_import
  end

  def initiatives_import_params
    params.fetch(:initiatives_import, {}).permit(:import, :card_type)
  end

  def card_type_from_scope
    params[:scope].split('_').first
  end

  def scorecard_type_from_scope(scope)
    case scope
    when 'transition' then 'TransitionCard'
    when 'sdgs_alignment_cards' then 'SustainableDevelopmentGoalAlignmentCard'
    else
      current_account.default_scorecard_type&.name || 'TransitionCard'
    end
  end
end

app/controllers/initiatives_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class InitiativesController < ApplicationController
  before_action :set_initiative, only: %i[show edit update destroy]
  before_action :set_focus_area_groups, only: [:show]
  before_action :set_scorecards_and_types, only: %i[show new edit]

  add_breadcrumb 'Initiatives', :initiatives_path

  def index
    base_scope = policy_scope(Initiative).send(scope_from_params).includes(:organisations).order(sort_order)

    respond_to do |format|
      format.html do
        @initiatives = base_scope.page params[:page]
      end
      format.csv do
        @initiatives = base_scope.all
        send_data initiatives_to_csv(@initiatives), type: Mime[:csv], filename: "#{export_filename}.csv"
      end
    end
  end

  def show
    @grouped_checklist_items = @initiative.checklist_items_ordered_by_ordered_focus_area

    add_breadcrumb @initiative.name
  end

  def new
    @scorecard = params[:scorecard_id].present? ? policy_scope(Scorecard).find(params[:scorecard_id]) : nil
    @initiative = Initiative.new(scorecard: @scorecard)
    authorize @initiative

    add_breadcrumb 'New Initiative'
  end

  def edit
    add_breadcrumb @initiative.name
  end

  def create
    @initiative = Initiative.new(initiative_params)
    authorize @initiative

    if @initiative.save
      ::SynchronizeLinkedInitiative.call(@initiative) if @initiative.scorecard.linked?

      redirect_to initiatives_path, notice: 'Initiative was successfully created.'
    else
      render :new
    end

  end

  def update
    linked_initiative = @initiative.linked_initiative

    if @initiative.update(initiative_params)
      if params[:unlink_initiative]
        linked_initiative.update(linked: false) if linked_initiative.present?
        @initiative.update(linked: false)
      elsif @initiative.linked?
        ::SynchronizeLinkedInitiative.call(@initiative, linked_initiative)
      end

      redirect_to initiatives_path, notice: 'Initiative was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @initiative.destroy
    redirect_to initiatives_url, notice: 'Initiative was successfully deleted.'
  end

  def content_subtitle
    subtitle = (@initiative&.name.presence || super)

    @initiative&.archived? ? subtitle + ' [ARCHIVED]' : subtitle
  end

  # NOTE Will move this to the checklist controller, where it belongs
  def edit_checklist_item
    @checklist_item = ChecklistItem.find(params[:id])
    authorize @checklist_item
    render partial: 'checklist_item_form', locals: { checklist_item: @checklist_item }
  end

  def linked
    initiative = policy_scope(Initiative).find(params[:initiative_id]).linked_initiative

    authorize initiative, :show?

    redirect_to initiative_path(initiative)
  end

  private

  def export_filename
    if current_account.scorecard_types.count > 1
      "initiatives_for_#{scope_from_params}_#{Date.today.strftime('%Y_%m_%d')}"
    else
      "initiatives_#{Date.today.strftime('%Y_%m_%d')}"
    end
  end

  def initiatives_to_csv(initiatives)
    max_organisation_index = initiatives.map(&:organisations).map(&:count).max
    max_subsystem_tag_index = initiatives.map(&:subsystem_tags).map(&:count).max

    CSV.generate(force_quotes: true) do |csv|
      csv << ([
        'Name',
        'Description',
        "#{Scorecard.model_name.human} Name",
        'Started At',
        'Finished At',
        'Contact Name',
        'Contact Email',
        'Contact Phone',
        'Contact Website',
        'Contact Position'
      ] + 1.upto(max_organisation_index).map do |index|
        "Organisation #{index} Name"
      end + 1.upto(max_subsystem_tag_index).map do |index|
        "Subsystem Tag #{index} Name"
      end) + ['Notes']

      initiatives.each do |initiative|
        organisations = initiative.organisations.limit(max_organisation_index)
        organisation_memo = Array.new(max_organisation_index, '')

        organisation_names = organisations.each_with_index.each_with_object(organisation_memo) do |(org, index), memo|
          memo[index] = org.try(:name)
        end

        subsystem_tags = initiative.subsystem_tags.limit(max_subsystem_tag_index)
        subsystem_tag_memo = Array.new(max_subsystem_tag_index, '')

        subsystem_tag_names = subsystem_tags.each_with_index.each_with_object(subsystem_tag_memo) do |(subsystem_tag, index), memo|
          memo[index] = subsystem_tag.try(:name)
        end

        csv << ([
          initiative.name,
          initiative.description,
          initiative.scorecard.try(:name),
          initiative.started_at,
          initiative.finished_at,
          initiative.contact_name,
          initiative.contact_email,
          initiative.contact_phone,
          initiative.contact_website,
          initiative.contact_position
        ] + organisation_names + subsystem_tag_names + [initiative.notes.to_plain_text.gsub(/\n/, ' ')])
      end
    end
  end

  def set_focus_area_groups
    @focus_areas_groups = FocusAreaGroup
                          .includes(:video_tutorial, focus_areas: :video_tutorial)
                          .where(scorecard_type: @initiative.scorecard.type)
                          .order(:position)
  end

  def set_initiative
    @initiative = Initiative.find(params[:id])
    authorize @initiative
  end

  def scope_from_params
    if params[:scope].blank? || !params[:scope].in?(%w[transition_cards sdgs_alignment_cards])
      case current_account.default_scorecard_type&.name
      when 'TransitionCard' then :transition_cards
      when 'SustainableDevelopmentGoalAlignmentCard' then :sdgs_alignment_cards
      else
        raise "Unknown scorecard_type.name '#{current_account.default_scorecard_type.name}'"
      end
    else
      params[:scope].to_sym
    end
  end

  # SMELL: Duplication of code in reports_controller
  ScorecardType = Struct.new('ScorecardType', :name, :scorecards)

  def set_scorecards_and_types
    @scorecards = policy_scope(Scorecard).order(:name)

    @scorecard_types = current_account.scorecard_types.map do |scorecard_type|
      ScorecardType.new(
        scorecard_type.model_name.human.pluralize,
        policy_scope(Scorecard).order(:name).where(type: scorecard_type.name)
      )
    end
  end

  def initiative_params
    params.fetch(:initiative, {}).permit(
      :name,
      :description,
      :scorecard_id,
      :started_at,
      :finished_at,
      :archived_on,
      :dates_confirmed,
      :contact_name,
      :contact_email,
      :contact_phone,
      :contact_website,
      :contact_position,
      :notes,
      initiatives_organisations_attributes: %i[
        organisation_id id _destroy
      ],
      initiatives_subsystem_tags_attributes: %i[
        subsystem_tag_id id _destroy
      ]
    ).tap do |params|
      # Remove organisations that are already assigned
      params[:initiatives_organisations_attributes].reject! do |_key, value|
        value[:id].blank? &&
          params[:initiatives_organisations_attributes].values.find do |attributes|
            (value[:organisation_id] == attributes[:organisation_id]) &&
              attributes[:id].present?
          end
      end

      # Remove duplicates
      params[:initiatives_organisations_attributes] = ActionController::Parameters.new(
        params[:initiatives_organisations_attributes].to_h.invert.invert
      ).permit!

      # Remove subsystem tags that are already assigned
      params[:initiatives_subsystem_tags_attributes].reject! do |_key, value|
        value[:id].blank? &&
          params[:initiatives_subsystem_tags_attributes].values.find do |attributes|
            (value[:subsystem_tag_id] == attributes[:subsystem_tag_id]) &&
              attributes[:id].present?
          end
      end

      # Remove duplicates
      params[:initiatives_subsystem_tags_attributes] = ActionController::Parameters.new(
        params[:initiatives_subsystem_tags_attributes].to_h.invert.invert
      ).permit!
    end
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/initiatives_helper.rb
# frozen_string_literal: true

module InitiativesHelper
  def scorecard_label(initiative)
    if initiative.new_record? || initiative.scorecard.nil?
      current_account.scorecard_types.map { |type| type.model_name.human }.join(' / ')
    else
      safe_join([
                  content_tag(:span, initiative.scorecard.model_name.human.to_s, style: 'margin-right: 10px'),
                  link_to(
                    content_tag(
                      :i,
                      '',
                      class: 'fa fa-external-link'
                    ),
                    transition_card_path(initiative.scorecard),
                    id: 'initiative-detail-scorecard-link'
                  )
                ])
    end
  end

  def initiatives_characteristics_title(initiative)
    case initiative.scorecard.type
    when 'TransitionCard' then 'Initiative Characteristics'
    when 'SustainableDevelopmentGoalAlignmentCard' then 'Initiative SDGs Targets'
    end
  end

  def link_to_video_tutorial(video_tutorial)
    return '' if video_tutorial.blank?

    link_to(
      video_tutorial_path(video_tutorial),
      class: 'video-tutorial-wrapper',
      data: {
        video_tutorial_link: video_tutorial_path(video_tutorial),
        video_tutorial_title: video_tutorial.name
      }
    ) do
      safe_join([content_tag(:i, '', class: 'fa fa-youtube-play')])
    end
  end

  def linked_initiative_warning(initiative)
    return '' if initiative.blank?
    return '' if initiative.scorecard.blank?

    return '' unless initiative.new_record?
    return '' unless initiative.scorecard.linked?
    return '' if initiative.linked_initiative.present?

    content_tag(:div, class: 'form-group row alert alert-warning') do
      content_tag(:strong, 'Note: ', class: 'mr-1') +
        "This initiative belongs to a linked #{initiative.scorecard.model_name.human}. " \
        'Saving this initiative will automaically create a linked initiative in the other card.'
    end
  end

  def initiative_tab_title(scorecard_type)
    case scorecard_type.name
    when 'TransitionCard' then 'Initiatives for Transition Cards'
    when 'SustainableDevelopmentGoalAlignmentCard' then 'Initiatives for SDGs Alignment Cards'
    end
  end

  def initiative_scope(scorecard_type)
    case scorecard_type.name
    when 'TransitionCard' then :transition_cards
    when 'SustainableDevelopmentGoalAlignmentCard' then :sdgs_alignment_cards
    end
  end

  def initiative_tab_class(scorecard_type, scope)
    case scorecard_type.name
    when 'TransitionCard'
      scope.blank? || scope == 'transition_cards' ? 'active' : ''
    when 'SustainableDevelopmentGoalAlignmentCard'
      scope == 'sdgs_alignment_cards' ? 'active' : ''
    end + ' nav-link'
  end

  def initiative_scorecard_types
    current_account.scorecard_types.map do |scorecard_type|
      [scorecard_type.model_name.human.pluralize, scorecard_type.name]
    end
  end

  def initiative_export_button_tooltip_title(params)
    if current_account.scorecard_types.count > 1
      "Export #{initiative_tab_title(scorecard_type_from_params(params))} to CSV"
    else
      'Export Initiatives to CSV'
    end
  end

  private

  # SMELL: Duplicate of code in initiatives_controller.rb
  def scorecard_type_from_params(params)
    if params[:scope].blank? || !params[:scope].in?(%w[transition_cards sdgs_alignment_cards])
      current_account.default_scorecard_type
    else
      case params[:scope].to_sym
      when :sdgs_alignment_cards then SustainableDevelopmentGoalAlignmentCard
      when :transition_cards then TransitionCard
      end
    end
  end
end

app/views/initiatives/_checklist_item_description.html.erb
<%- if checklist_item.characteristic.description.present? %>
  <%= 
    link_to(
      description_characteristic_path(checklist_item.characteristic), 
      class: 'remote-link description-characteristic-link',
      data: {
        toggle: "tooltip",
        placement: "top", 
        title: "More information" 
      }
    ) do
      safe_join([content_tag(:i, '', class: "fas fa-info-circle")])
    end
  %>  
<%- end -%>

app/views/initiatives/_checklist_item_video_tutorial.html.erb
<%- if video_tutorial.present? %>
  <%=
    link_to(
      video_tutorial_path(video_tutorial),
      class: 'video-tutorial-wrapper',
      data: {
        video_tutorial_link: video_tutorial_path(video_tutorial),
        video_tutorial_title: video_tutorial.name
      }
    ) do
      safe_join([content_tag(:i, '', class: "fa fa-youtube-play")])
    end
  %>
<%- end %>

app/views/initiatives/_checklist_items.html.erb
<div class="tab-pane active" id="checklist-items-tab">
  <div class="container">
    <div class="row tab-content-header p-3">
      <div class="col-sm">
        <div class="float-left pt-1">
          <h3><%= initiatives_characteristics_title(@initiative) %></h3>
        </div>
        <div class="float-right">

          <%= link_to "#{@initiative.scorecard.model_name.human} Details", scorecard_path(@initiative.scorecard), class: 'btn btn-primary float-right' %>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="box-group" id="accordion">
        <% @focus_areas_groups.each do |focus_area_group| %>
          <div class="initiative-characteristics-container">
            <div class="focus-area-group-container">
              <h4 class="focus-area-group-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapsable-focus-area-group-<%= focus_area_group.id %>">
                  <%= focus_area_group.name %>
                  <%= link_to_video_tutorial(focus_area_group.video_tutorial) %>
                </a>
              </h4>
            </div>
            <div id="collapsable-focus-area-group-<%= focus_area_group.id %>" class="panel-collapse collapse <%= "show" if focus_area_group == @focus_areas_groups.first %> ">
              <% focus_area_group.focus_areas.order(:position).each do |focus_area| %>
                <div class="box-body">
                  <h3 class="focus-area">
                    <%- if @initiative.scorecard.type == 'TransitionCard' -%>
                      <%= focus_area.name %>
                      <%= link_to_video_tutorial(focus_area.video_tutorial) %>
                    <%- else -%>
                      <a data-toggle="collapse" data-parent="#collapsable-focus-area-group-<%= focus_area_group.id %>" href="#collapsable-focus-area-<%= focus_area.id %>">
                        <%= focus_area.name %>
                        <%= link_to_video_tutorial(focus_area.video_tutorial) %>
                      </a>
                    <%- end -%>
                  </h3>
                  <% checklist_items = @grouped_checklist_items.to_a.find_all { |ci| ci.characteristic.focus_area.id == focus_area.id } %>
                  <div id="collapsable-focus-area-<%= focus_area.id %>" class="panel-collapse collapse <%= "show" if @initiative.scorecard.type == 'TransitionCard' || focus_area == focus_area_group.focus_areas.first %> ">
                    <ul class="checklist-items">
                      <% checklist_items.each do |checklist_item| %>
                        <div
                            data-controller="comments"
                            data-load-path="<%=edit_checklist_item_path(checklist_item)%>"
                            data-state-path="<%=checklist_item_path(checklist_item)%>"
                        >
                          <li>
                            <label>
                              <%= checklist_item_badge(checklist_item) %>

                              <span class="characteristic-name <%= current_comment_status_style(checklist_item) %>" data-comments-target="characteristic">
                                <%= link_to(
                                      '#characteristic_comment',
                                      class: 'characteristic-comment',
                                      data: {
                                        action: "comments#open",
                                        id: checklist_item.id,
                                        initiative_id: checklist_item.initiative_id
                                      }
                                    )  do
                                      checklist_item.characteristic.name
                                    end
                                %>
                              </span>
                              <%= link_to(
                                '#characteristic_comment',
                                class: 'characteristic-comment',
                                data: {
                                  action: "comments#open",
                                  id: checklist_item.id,
                                  initiative_id: checklist_item.initiative_id,
                                  toggle: "tooltip",
                                  placement: "top",
                                  title: "Edit comments"
                                }
                              ) do
                                safe_join([content_tag(:i, '', class: "fa fa-comments-o")])
                              end %>
                              <%= render 'checklist_item_video_tutorial', video_tutorial: checklist_item.characteristic.video_tutorial %>
                              <%= render 'checklist_item_description', checklist_item: checklist_item %>
                            </label>

                            <div data-comments-target="form"></div>
                          </li>
                        </div>
                      <%- end -%>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/initiatives/_details.html.erb
<div class="tab-pane" id="details-tab">
  <%= simple_form_for(@initiative, role: 'form', html: { class: 'form-horizontal record-form' } ) do |f| %>
    <%= f.error_notification %>
    <%= form_header(@initiative) %>
    <%= f.input :name %>
    <%= f.input :description %>
    <hr>
    <%- if current_account.scorecard_types.count > 1 %>
      <%= f.association :scorecard, collection: @scorecard_types, as: :grouped_select, group_method: :scorecards, label: scorecard_label(@initiative) %>
    <%- else %>
      <%= f.association :scorecard, collection: @scorecards, label: scorecard_label(@initiative) %>
    <%- end %>

    <%- if @initiative.linked_initiative.present? %>
      <div class="form-group row grouped_select optional initiative_scorecard form-group-valid">
        <label class="col-sm-3 col-form-label grouped_select optional">
          <span style="margin-right: 10px">Linked Initiative</span>
          <%= link_to initiative_path(@initiative.linked_initiative), target: "_blank", rel: "nofollow" do %>
            <i class="fa fa-external-link" aria-hidden="true"></i>
          <% end %>
        </label>
        <div class="col-sm-7">
          <%= text_field_tag :linked_initiative, @initiative.linked_initiative_name, readonly: true, class: "form-control string optional" %>
        </div>
        <div class="col-sm-2">
          <label class="btn btn-secondary">
            <%= check_box_tag(:unlink_initiative, true, false) %> Unlink
          </label>
        </div>
      </div>
    <% end %>

    <hr>
    <%= render 'transition_cards/form_tabs/organisations', f: f %>
    <hr>
    <%= render 'transition_cards/form_tabs/subsystem_tags', f: f %>
    <hr>
    <%= f.input :started_at, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.started_at) } %>
    <%= f.input :finished_at, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.finished_at) } %>
    <%- if policy(@initiative).archive? -%>
      <hr>
      <%= f.input :archived_on, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.archived_on) }%>
    <%- end -%>
    <hr>
    <%= f.input :contact_name %>
    <%= f.input :contact_email %>
    <%= f.input :contact_website %>
    <%= f.input :contact_position %>
    <hr>
    <%= f.input :notes, as: :rich_text_area %>
    <div class='d-flex justify-content-end'>
      <%= f.button :submit, class: 'btn btn-primary mr-3' %>
    </div>
  <% end %>
</div>

app/views/initiatives/_form.html.erb
<%= simple_form_for(@initiative, role: 'form', html: { class: 'form-horizontal record-form' }) do |f| %>
  <%= f.error_notification %>
  <%= form_header(@initiative) %>

  <%= linked_initiative_warning(@initiative) %>

  <%= f.input :name, required: true  %>
  <%= f.input :description %>

  <%=
    f.association(
      :scorecard,
      collection: policy_scope(Scorecard),
      required: true,
      label: scorecard_label(@initiative)
    )
  %>
  <hr>
  <%= render 'transition_cards/form_tabs/organisations', f: f %>
  <%= render 'transition_cards/form_tabs/subsystem_tags', f: f %>
  <%= f.input :started_at, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.started_at) } %>
  <%= f.input :finished_at, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.finished_at) } %>
  <%- if policy(@initiative).archive? -%>
    <hr>
    <%= f.input :archived_on, as: :string, input_html: { data: { behaviour: "datepicker" }, value: format_date(f.object.archived_on) }%>
  <%- end -%>
  <hr>
  <%= f.input :contact_name %>
  <%= f.input :contact_email %>
  <%= f.input :contact_website %>
  <%= f.input :contact_position %>
  <%= f.input :notes, as: :rich_text_area %>
  <%= render_form_button(f) %>
<% end %>

app/views/initiatives/edit.html.erb
<%= render 'form', initiative: @initiative %>

app/views/initiatives/index.html.erb
<% content_for :page_actions do %>
  <%=
    if policy(Initiative).create?
      create_new_button(new_initiative_path)
    end
  %>
  <%=
    link_to(
      initiatives_path(scope: params[:scope], format: :csv),
      class: 'btn btn-primary',
      data: {
        toggle: 'tooltip',
        title: initiative_export_button_tooltip_title(params)
      }
    ) do
      safe_join([content_tag(:i, '', class: "fa fa-download"), ' Export'])
    end
  %>
  <%=
    link_to(new_initiatives_import_path(scope: params[:scope]), class: 'btn btn-primary') do
      safe_join([content_tag(:i, '', class: "fa fa-upload"), ' Import'])
    end
  %>
<% end %>

<%- if current_account.scorecard_types.size > 1 %>
  <div id="initiatives-nav" class="nav-tabs-custom" data-initiatives-target="cardTypeTab">
    <ul class="nav nav-tabs">
      <%- current_account.scorecard_types.each do |scorecard_type| %>
        <li class="nav-item">
          <%=
            link_to(
              initiative_tab_title(scorecard_type),
              initiatives_path(scope: initiative_scope(scorecard_type)),
              class: initiative_tab_class(scorecard_type, params[:scope])
            )
          %>
        </li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

<%= render 'table' %>

app/views/initiatives/new.html.erb
<%= render 'form', initiative: @initiative %>

app/views/initiatives/show.html.erb
<div id="initiatives-nav" class="nav-tabs-custom">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#checklist-items-tab" class="nav-link active" data-toggle="tab">
        <%= initiatives_characteristics_title(@initiative) %>
      </a>
    </li>
    <li class="nav-item">
      <a href="#details-tab" class="nav-link" data-toggle="tab">Details</a>
    </li>
  </ul>
  <div class="tab-content">
    <%= render 'checklist_items' %>
    <%= render 'details' %>
  </div>
</div>