config/routes.rb
Rails.application.routes.draw do

  resources :subsystem_tags
  namespace :initiatives do
    resources :imports, only: [:new, :create, :update]
  end

  resources :checklist_items, only: [:show, :edit, :update]

  namespace :organisations do
    resources :imports, only: [:new, :create, :update]
  end

  namespace :transition_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, skip: [:registrations], :controllers => { :invitations => 'invitations' }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :communities
  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics, only: [:show],
      controller: 'sustainable_development_goal_alignment_cards',
      action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared, constraints: {
    id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
  }, only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show],
      controller: 'shared',
      action: 'characteristic'
  end

  resources :stakeholder_types
  resources :users do
    post :stop_impersonating, on: :collection

    member do
      get 'remove_from_account'
    end
  end

  resources :video_tutorials
  resource :welcome_message, only: [:show]
  resources :wicked_problems

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
    end
  end

  resources :search_results, only: [:index, :show]

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'

  namespace :system do
    resources :stakeholder_types
    resources :users do
      post :impersonate, on: :member

      member do
        get 'undelete'
        get 'resend_invitation'
      end
    end
  end

  root to: "home#index"
end

app/models/transition_card.rb
# frozen_string_literal: true
class TransitionCard < Scorecard

end

app/controllers/transition_cards_controller.rb
class TransitionCardsController < ScorecardsController

  add_breadcrumb TransitionCard.model_name.human.pluralize, :transition_cards_path

  def index
    @scorecards = policy_scope(Scorecard).where(type: 'TransitionCard').order(sort_order).page params[:page]
  end

  def content_title
    'Transition Cards'
  end

  def scorecard_key_param
    :transition_card
  end

  def scorecard_class_name
    'TransitionCard'
  end
end

app/views/transition_cards/show_tabs/_grid.html.erb
<div class="box-body scorecard-matrix transition-card-matrix pl-3" data-transition-cards-target="grid">
  <div class="outer">
    <div class="inner">
      <table class="pre-scrollable">
        <thead>
          <tr>
            <th>&nbsp;</th>
            <% @focus_areas.each_with_index do |focus_area, index| %>
              <th colspan="<%= focus_area.characteristics.size %>" class="legend">
                <div data-toggle="tooltip" data-placement="top" title="<%= focus_area.name %>">
                  <span class="text-color<%="#{index+1}"%>">Focus Area <%= index + 1 %>
                  </span>
                </div>
              </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |result| %>
          <tr>
            <th>
              <%=
                link_to_if(
                  !(defined?(disable_links) && disable_links),
                  result.dig('initiative', :name),
                  initiative_path(id: result.dig('initiative', :id)),
                  class: 'truncate',
                  data: {
                    toggle: 'tooltip',
                    placement: 'top',
                    title: result.dig('initiative', :name)
                  }
                ) do
                  tag.span(result.dig('initiative', :name), class: 'truncate')
                end
              %>
            </th>
            <% @characteristics.each do |characteristic| %>
              <td
                data-toggle="tooltip"
                data-placement="left"
                data-container=".inner"
                data-status="<%= result.dig(characteristic.id.to_s, :status) %>"
                title="<%= result.dig(characteristic.id.to_s, :name) %>"
                class="<%= cell_class(result, @focus_areas, characteristic) %>">
                <span>&nbsp;</span>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr class="chars">
            <td>
              &nbsp;
            </td>
            <% @characteristics.each do |characteristic| %>
              <td>
                <span class="text-color<%= @focus_areas.index(characteristic.focus_area)+1%>"><%= characteristic.name %></span>
              </td>
            <% end %>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/transition_cards/show_tabs/_scorecard.html.erb
<div class="container-fluid" data-controller='transition-cards'>
  <div class="row tab-content-header p-3">
    <div class="col-sm">
      <div class="float-left">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
          </div>
          <input
            type="text"
            class="form-control"
            id="transition_card_select_date"
            autocomplete="off"
            data-scorecard-id="<%=@scorecard.id%>" placeholder="Select Date"
            <%= "data-selected-date=\"#{@selected_date}\"" unless @selected_date.blank? %>
          >
        </div>
      </div>
      <div class="float-left">
        <%= link_to('#', class: 'btn btn-primary', id: 'daterange-clear-btn', data: { toggle: "tooltip" }, title: "Clear date") do
          content_tag(:i, '', class: "fa fa-undo")
        end %>
      </div>

      <%- if policy(:sidebar).show_subsystem_tags_link? %>
        <div class="float-left" style="padding-right: 5px; padding-left: 5px;">
          <div class="input-group">

            <select multiple="multiple" class="form-control" id="subsystem-tags" style="min-width: 300px;" data-scorecard-id="<%=@scorecard.id%>">
              <%- @selected_tags.each do |selected_tag| %>
                  <option value="<%= selected_tag.id %>" selected="selected"><%= selected_tag.text %></option>
              <%- end %>
            </select>
          </div>
        </div>
      <%- end %>

      <div class="float-right">
        <%= render partial: '/scorecards/show_tabs/status_filter' %>

        <%- print_transition_card_path = if @selected_date
            transition_card_path(@scorecard, format: :pdf, selected_date: @selected_date, key: SecureRandom.urlsafe_base64(5))
          else
            transition_card_path(@scorecard, format: :pdf, key: SecureRandom.urlsafe_base64(5))
          end
        %>
        <%= link_to(print_transition_card_path, class: 'btn btn-primary', data: { toggle: "tooltip"}, title: "Print") do
          content_tag(:i, '', class: "fa fa-print")
        end %>
        <%= link_to(show_shared_link_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Share") do
          content_tag(:i, '', class: "fa fa-share-alt")
        end %>
        <% if policy(:scorecard).copy_options? %>
          <%= link_to(copy_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Copy") do
            content_tag(:i, '', class: "fa fa-files-o")
          end %>
        <% end %>
        <% if policy(:scorecard).merge_options? %>
          <%= link_to(merge_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Merge") do
            content_tag(:i, '', class: "fa fa-file-text-o")
          end %>
        <% end %>

      </div>
    </div>
  </div>
  <%= render partial: 'transition_cards/show_tabs/grid' %>
</div>