config/routes.rb
Rails.application.routes.draw do

  resources :subsystem_tags
  namespace :initiatives do
    resources :imports, only: [:new, :create, :update]
  end

  resources :checklist_items, only: [:show, :edit, :update]

  namespace :organisations do
    resources :imports, only: [:new, :create, :update]
  end

  namespace :transition_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, skip: [:registrations], :controllers => { :invitations => 'invitations' }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :communities
  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics, only: [:show],
      controller: 'sustainable_development_goal_alignment_cards',
      action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared, constraints: {
    id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
  }, only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show],
      controller: 'shared',
      action: 'characteristic'
  end

  resources :stakeholder_types
  resources :users do
    post :stop_impersonating, on: :collection

    member do
      get 'remove_from_account'
    end
  end

  resources :video_tutorials
  resource :welcome_message, only: [:show]
  resources :wicked_problems

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
    end
  end

  resources :search_results, only: [:index, :show]

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'

  namespace :system do
    resources :stakeholder_types
    resources :users do
      post :impersonate, on: :member

      member do
        get 'undelete'
        get 'resend_invitation'
      end
    end
  end

  root to: "home#index"
end

app/models/focus_area_group.rb
# frozen_string_literal: true
class FocusAreaGroup < ApplicationRecord
  acts_as_paranoid

  default_scope { order(:position) }
  
  attr_accessor :video_tutorial_id

  has_many :focus_areas, dependent: :restrict_with_error
  has_one :video_tutorial, as: :linked

  validates :position, presence: true
  
  def video_tutorial_id=(value)
    return if value.blank?
    tutorial = VideoTutorial.where(id: value).first
    tutorial.update_attribute(:linked, self) if tutorial
  end
  
  def video_tutorial_id
    video_tutorial.try(:id)
  end
end

app/controllers/focus_area_groups_controller.rb
class FocusAreaGroupsController < ApplicationController
  before_action :set_focus_area_group, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "System", :focus_area_groups_path

  def index
    @focus_area_groups = policy_scope(FocusAreaGroup).unscoped.order(sort_order).page params[:page]
  end

  def show
  end

  def new
    @focus_area_group = FocusAreaGroup.new
    authorize @focus_area_group
  end

  def edit
  end

  def create
    @focus_area_group = FocusAreaGroup.new(focus_area_group_params)
    authorize @focus_area_group

    if @focus_area_group.save
      redirect_to focus_area_groups_path, notice: 'Focus area group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @focus_area_group.update(focus_area_group_params)
      redirect_to focus_area_groups_path, notice: 'Focus area group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @focus_area_group.destroy
    redirect_to focus_area_groups_url, notice: 'Focus area group was successfully deleted.'
  end

  def content_subtitle
    @focus_area_group&.name.presence || super
  end

  private

  def set_focus_area_group
    @focus_area_group = FocusAreaGroup.find(params[:id])
    authorize @focus_area_group
  end

  def focus_area_group_params
    params.fetch(:focus_area_group, {}).permit(:name, :description, :position, :video_tutorial_id)
  end
end

app/helpers/focus_area_groups_helper.rb
module FocusAreaGroupsHelper
  def options_for_scorecard_type
    [SustainableDevelopmentGoalAlignmentCard, TransitionCard].map do |klass|
      [klass.name.demodulize.titleize, klass.name]
    end
  end
end

app/views/focus_area_groups/_form.html.erb
<%= simple_form_for(@focus_area_group, role: 'form', html: { class: 'form-horizontal record-form' }) do |f| %>
  <%= f.error_notification %>
  <%= form_header(@focus_area_group) %>
  <%= f.input :name %>
  <%= f.input :description , as: :string %>
  <%= f.input :scorecard_type, collection: options_for_scorecard_type, label: 'Scorecard Type', include_blank: false %>
  <%= f.input :position %>
  <%= f.input :video_tutorial_id, collection: VideoTutorial.all,
    hint: 'Any video tutorial can only be assigned to one other record at a time. Link a tutorial to this record removes any other link elsewhere.'
  %>
  <%= render_form_button(f) %>
<% end %>

app/views/focus_area_groups/edit.html.erb
<%= render 'form', focus_area_group: @focus_area_group %>

app/views/focus_area_groups/index.html.erb
<% content_for :page_actions do %>
  <%= create_new_button(new_focus_area_group_path) %>
<% end %>

<div class="box">
  <div class='box-body no-padding'>
  <%= table_for @focus_area_groups, :table_html => { :class => "table table-striped" },
                        :sortable => true,
                        :data_row_html => {
                          id: lambda { |focus_area_group| "focus_area_group-#{focus_area_group.id}" },
                          class: 'table-actions'
                        } do |table| %>
    <% table.column :name, link_action: :edit, formatter: lambda { |text| truncate_text(text, 30) } %> %>
    <% table.column :description, formatter: lambda { |text| truncate_text(text, 100) } %>
    <% table.column :scorecard_type %>
    <% table.column :position %>
    <% table.column data: "Modify", link_action: :edit %>
    <% table.column data: "Delete", link_method: :delete, link_confirm: "Are you sure?" %>
    <% table.footer do %>
      <div class="float-right">
        <%= paginate @focus_area_groups %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/focus_area_groups/new.html.erb
<%= render 'form', focus_area_group: @focus_area_group %>

app/views/focus_area_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_focus_area_group_path(@focus_area_group) %> |
<%= link_to 'Back', focus_area_groups_path %>