config/routes.rb
Rails.application.routes.draw do

  resources :subsystem_tags
  namespace :initiatives do
    resources :imports, only: [:new, :create, :update]
  end

  resources :checklist_items, only: [:show, :edit, :update]

  namespace :organisations do
    resources :imports, only: [:new, :create, :update]
  end

  namespace :transition_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: [:new, :create, :update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, skip: [:registrations], :controllers => { :invitations => 'invitations' }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :communities
  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics, only: [:show],
      controller: 'sustainable_development_goal_alignment_cards',
      action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared, constraints: {
    id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
  }, only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show],
      controller: 'shared',
      action: 'characteristic'
  end

  resources :stakeholder_types
  resources :users do
    post :stop_impersonating, on: :collection

    member do
      get 'remove_from_account'
    end
  end

  resources :video_tutorials
  resource :welcome_message, only: [:show]
  resources :wicked_problems

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
    end
  end

  resources :search_results, only: [:index, :show]

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'

  namespace :system do
    resources :stakeholder_types
    resources :users do
      post :impersonate, on: :member

      member do
        get 'undelete'
        get 'resend_invitation'
      end
    end
  end

  root to: "home#index"
end

app/models/reports/base.rb
# frozen_string_literal: true

module Reports
  class Base
    private

    def default_styles(package)
      header_styles(package).merge(
        {
          blue_normal: package.workbook.styles.add_style(fg_color: '386190', sz: 12, b: false),
          wrap_text: package.workbook.styles.add_style(
            alignment: { horizontal: :general, vertical: :bottom,
            wrap_text: true }
          ),
          date: date_style(package)
        }
      )
    end

    def date_style(package)
      package.workbook.styles.add_style(format_code: 'd/m/yy')
    end

    def header_styles(package)
      {
        h1: package.workbook.styles.add_style(fg_color: '386190', sz: 16, b: true),
        h2: package.workbook.styles.add_style(bg_color: 'dce6f1', fg_color: '386190', sz: 12, b: true),
        h3: package.workbook.styles.add_style(bg_color: 'dce6f1', fg_color: '386190', sz: 12, b: false),
      }
    end
  end
end

app/models/reports/subsystem_summary.rb
# frozen_string_literal: true

require 'csv'

module Reports
  class SubsystemSummary < Base
    attr_accessor :scorecard

    def initialize(scorecard)
      super()
      @scorecard = scorecard
    end

    # rubocop:disable Metrics/MethodLength
    # rubocop:disable Metrics/AbcSize
    def to_xlsx
      Axlsx::Package.new do |p|
        p.workbook.styles.fonts.first.name = 'Calibri'
        styles = default_styles(p)
        p.workbook.add_worksheet(name: 'Report') do |sheet|
          sheet.add_row([Time.now], style: styles[:date])
          add_title(sheet, styles)
          sheet.add_row
          add_summary(sheet, styles)
          sheet.add_row
          add_initiatives_per_subsystem(sheet, styles)
          sheet.add_row
          add_organisations_per_subsystem(sheet, styles)
        end
      end.to_stream
    end
    # rubocop:enable Metrics/MethodLength
    # rubocop:enable Metrics/AbcSize

    private

    def add_title(sheet, styles)
      sheet.add_row([scorecard.model_name.human], style: styles[:h1]).add_cell(
        scorecard.name,
        style: styles[:blue_normal]
      )
      sheet.add_row(['Wicked problem / opportunity', scorecard.wicked_problem.name])
      sheet.add_row(['Community', scorecard.community&.name || 'MISSING DATA'])
    end

    def add_summary(sheet, styles)
      sheet.add_row(['Total Subsystems', total_subsystems], style: styles[:h1])
      sheet.add_row(['Total Partnering Organisations', total_partnering_organisations], style: styles[:h1])
      sheet.add_row(
        ["Total #{scorecard.model_name.human} Initiatives", total_transition_card_initiatives],
        style: styles[:h1]
      )
    end

    def add_initiatives_per_subsystem(sheet, styles)
      initiatives_per_subsystem = fetch_initiatives_per_subsystem
      max_initiatives = initiatives_per_subsystem.values.map(&:count).max || 0

      sheet.add_row(['Subsystem ', 'Total Initiatives'] + Array.new(max_initiatives, 'Initiatives'), style: styles[:h3])
      initiatives_per_subsystem.each do |subsystem, initiatives|
        sheet.add_row([subsystem, initiatives.count] + initiatives)
      end
    end

    def add_organisations_per_subsystem(sheet, styles)
      organisations_per_subsystem = fetch_organisations_per_subsystem
      max_organisations = organisations_per_subsystem.values.map(&:count).max || 0

      sheet.add_row(
        ['Subsystem ', 'Total Organisations'] + Array.new(max_organisations, 'Organisations'),
        style: styles[:h3]
      )
      organisations_per_subsystem.each do |subsystem, organisations|
        sheet.add_row([subsystem, organisations.count] + organisations)
      end
    end

    def total_partnering_organisations
      scorecard.unique_organisations.count
    end

    def total_transition_card_initiatives
      scorecard.initiatives.not_archived.count
    end

    # NOTE: Not sure what Emily requires here. The following code restricts the
    #       number of partnering organisations and initiatives to those that are
    #       part of the subsystems.
    #       The code above is the same as the code in Reports::TransitionCardStakeholders
    #
    # def total_partnering_organisations
    #   subsystem_tags_query.flat_map(&:initiatives).flat_map(&:organisations).uniq.count
    # end

    # def total_transition_card_initiatives
    #   subsystem_tags_query.flat_map(&:initiatives).uniq.count
    # end

    def total_subsystems
      subsystem_tags_query.uniq.count
    end

    def fetch_initiatives_per_subsystem
      subsystem_tags_query.each_with_object({}) do |subsystem, memo|
        memo[subsystem.name] = subsystem.initiatives.map(&:name).uniq.sort
      end
    end

    def fetch_organisations_per_subsystem
      subsystem_tags_query.each_with_object({}) do |subsystem, memo|
        memo[subsystem.name] = subsystem.initiatives.flat_map(&:organisations).flat_map(&:name).uniq.sort
      end
    end

    def subsystem_tags_query
      SubsystemTag
        .joins(:initiatives)
        .includes(:initiatives)
        .where('initiatives.archived_on is null or initiatives.archived_on > ?', Time.zone.now)
        .where('initiatives.scorecard_id': scorecard.id).distinct
        .order(:name)
    end
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class ReportsController < ApplicationController
  skip_after_action :verify_policy_scoped
  # skip_after_action :verify_authorized

  add_breadcrumb 'Reports', :reports_path

  ScorecardType = Struct.new('ScorecardType', :name, :scorecards)

  def index
    authorize(:report, :index?)

    @scorecards = policy_scope(Scorecard).order(:name)

    @scorecard_types =
      current_account.scorecard_types.map do |scorecard_type|
        ScorecardType.new(
          scorecard_type.model_name.human.pluralize,
          policy_scope(Scorecard).order(:name).where(type: scorecard_type.name)
        )
      end
  end

  def initiatives
    authorize(:report, :index?) # SMELL Incorrect policy check. Need to fix.

    @content_subtitle = 'Initiatives'
    add_breadcrumb(@content_subtitle)

    query = policy_scope(Initiative).joins(scorecard: %i[community wicked_problem])

    wicked_problem_ids = params[:report][:wicked_problems].reject { |e| e.to_s.empty? }
    community_ids = params[:report][:communities].reject { |e| e.to_s.empty? }

    query = query.where('scorecards.wicked_problem_id': wicked_problem_ids) if wicked_problem_ids

    query = query.where('scorecards.community_id': community_ids) if community_ids

    @results = query.select(
      :id,
      :name,
      :description,
      :created_at,
      :scorecard_id,
      'wicked_problems.name as wicked_problem_name',
      'communities.name as community_name',
      'scorecards.name as scorecard_name'
    ).distinct.page(params[:page])
  end

  def stakeholders
    authorize(:report, :index?)

    @content_subtitle = 'Stakeholders'
    add_breadcrumb(@content_subtitle)

    query = current_account.organisations.joins(:stakeholder_type, initiatives: [scorecard: %i[wicked_problem community]])

    query = query.where(stakeholder_type_id: params[:report][:stakeholder_type]) unless params[:report][:stakeholder_type].blank?

    unless params[:report][:wicked_problem].blank?
      query = query.where('scorecards.wicked_problem_id': params[:report][:wicked_problem])
    end

    unless params[:report][:community].blank?
      query = query.where('scorecards.community_id': params[:report][:community])
    end

    @results = query.select(
      :id,
      :name,
      :description,
      :created_at,
      :stakeholder_type_id,
      'stakeholder_types.name as stakeholder_type_name',
      'wicked_problems.name as wicked_problem_name',
      'communities.name as community_name',
      'scorecards.name as scorecard_name'
    ).distinct.page(params[:page])
  end

  def transition_card_activity
    authorize(:report, :transition_card_activity?)

    @content_subtitle = "#{Scorecard.model_name.human} Activity"
    add_breadcrumb(@content_subtitle)

    @date_from = Date.parse(params[:report][:date_from]).beginning_of_day
    @date_to = Date.parse(params[:report][:date_to]).end_of_day
    @scorecard = current_account.scorecards.find(params[:report][:scorecard_id])

    @report = Reports::TransitionCardActivity.new(@scorecard, @date_from, @date_to)

    respond_to do |format|
      format.html
      format.xlsx do
        send_data(
          @report.to_xlsx.read,
          type: Mime[:xlsx],
          filename: "#{scorecard_activity_base_filename(@scorecard)}#{time_stamp_suffix}.xlsx"
        )
      end
    end
  end

  def transition_card_activity
    authorize(:report, :transition_card_activity?)

    @content_subtitle = "#{Scorecard.model_name.human} Activity"
    add_breadcrumb(@content_subtitle)

    @date_from = \
      ActiveSupport::TimeZone[current_user.time_zone]
        .parse(params[:report][:date_from])
        .beginning_of_day
        .utc

    @date_to = \
      ActiveSupport::TimeZone[current_user.time_zone]
        .parse(params[:report][:date_to])
        .end_of_day
        .utc

    @date_to = Date.parse(params[:report][:date_to]).end_of_day
    @scorecard = current_account.scorecards.find(params[:report][:scorecard_id])

    @report = Reports::TransitionCardActivity.new(@scorecard, @date_from, @date_to)

    respond_to do |format|
      format.html
      format.xlsx do
        send_data(
          @report.to_xlsx.read,
          type: Mime[:xlsx],
          filename: "#{scorecard_new_activity_base_filename(@scorecard)}#{time_stamp_suffix}.xlsx"
        )
      end
    end
  end

  def scorecard_comments
    authorize(:report, :index?)

    @content_subtitle = "#{Scorecard.model_name.human} Comments"
    add_breadcrumb(@content_subtitle)

    @scorecard = current_account
                 .scorecards
                 .includes(initiatives: [checklist_items: [characteristic: [focus_area: :focus_area_group]]])
                 .find(params[:report][:scorecard_id])

    @date = \
      ActiveSupport::TimeZone[current_user.time_zone]
        .parse(params[:report][:date])
        .end_of_day
        .utc

    @status = params[:report][:status]

    @report = Reports::ScorecardComments.new(@scorecard, @date, @status, current_user.time_zone)

    respond_to do |format|
      format.html
      format.xlsx do
        send_data(
          @report.to_xlsx.read,
          type: Mime[:xlsx],
          filename: "#{scorecard_new_comments_base_filename(@scorecard)}#{time_stamp_suffix}.xlsx",
          disposition: 'attachment'
        )
      end
    end
  end

  def transition_card_stakeholders
    authorize(:report, :index?)

    @content_subtitle = 'Transition Card Stakeholder Report'
    add_breadcrumb(@content_subtitle)

    @scorecard = current_account.scorecards.find(params[:report][:scorecard_id])
    @report = Reports::TransitionCardStakeholders.new(@scorecard)
    send_data(
      @report.to_xlsx.read,
      type: Mime[:xlsx],
      filename: "#{transition_card_stakeholders_base_filename(@scorecard)}#{time_stamp_suffix}.xlsx"
    )
  end

  def subsystem_summary
    authorize(:report, :subsystem_summary?)

    @scorecard = current_account.scorecards.find(params[:report][:scorecard_id])
    @report = Reports::SubsystemSummary.new(@scorecard)
    send_data(
      @report.to_xlsx.read,
      type: Mime[:xlsx],
      filename: "#{subsystem_summary_base_filename(@scorecard)}#{time_stamp_suffix}.xlsx"
    )
  end

  private

  def scorecard_activity_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_Activity"
  end

  def scorecard_new_activity_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_New_Activity"
  end

  def scorecard_new_comments_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_New_Comments"
  end

  def scorecard_comments_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_Comments"
  end

  def transition_card_stakeholders_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_Stakeholders"
  end

  def subsystem_summary_base_filename(scorecard)
    "#{report_filename_prefix(scorecard)}_Subsystems"
  end

  def report_filename_prefix(scorecard)
    scorecard.model_name.human.delete(' ')
  end

  def time_stamp_suffix
    Time.zone.now.strftime('_%Y_%m_%d')
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
  def options_for_comment_statuses
    ChecklistItemComment.statuses.keys.map { |status| [status.titleize, status] }
  end

  def activity_report_name
    multiple_scorecards_types? ? 'Activity Report' : "#{default_scorecard_type_name} Activity Report"
  end

  def comments_report_name
    multiple_scorecards_types? ? 'Comments Report' : "#{default_scorecard_type_name} Comments Report"
  end

  def stakeholder_report_name
    multiple_scorecards_types? ? 'Stakeholder Report' : "#{default_scorecard_type_name} Stakeholder Report"
  end

  def report_scorecard_label
    multiple_scorecards_types? ? 'Select Card' : default_scorecard_type_name
  end

  private

  def default_scorecard_type_name
    current_account.scorecard_types.first.model_name.human
  end

  def multiple_scorecards_types?
    current_account.scorecard_types.count > 1
  end
end

app/views/reports/_scorecard_selector.html.erb
<%- if current_account.scorecard_types.count > 1 %>
<%= f.input :scorecard_id, collection: @scorecard_types, as: :grouped_select, group_method: :scorecards, label: report_scorecard_label %>
<%- else %>
<%= f.input :scorecard_id, collection: @scorecards, label: report_scorecard_label %>
<%- end %>

app/views/reports/index.html.erb
<div class="row reports">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header with-border">
        <h3 class="card-title"><i class="fa fa-pie-chart fa-report report-icon"></i> <%= stakeholder_report_name %></h3>
      </div>
      <%= simple_form_for :report, url: transition_card_stakeholders_reports_path(format: :xlsx), role: 'form', html: { class: 'form-horizontal' } do |f| %>
      <div class="card-body">
        <p>This report provides details on the number of partnering organisations, the initiatives they are working on and their stakeholder type.</p>
        <%= render partial: 'scorecard_selector', locals: { f: f } %>
      </div>
      <div class="card-footer">
        <%= button_tag('Download', type: 'submit', class: "btn btn-primary float-right") %>
      </div>
      <% end %>
    </div>
  </div>

  <%- if policy(:report).subsystem_summary? %>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header with-border">
          <h3 class="card-title"><i class="fa fa-pie-chart fa-report report-icon"></i> Subsystem Report</h3>
        </div>
        <%= simple_form_for :report, url: subsystem_summary_reports_path(format: :xlsx), role: 'form', html: { class: 'form-horizontal' } do |f| %>
        <div class="card-body">
          <p>This report shows a summary of the interactons between subsystems, organisations and initiatives.</p>
          <%= render partial: 'scorecard_selector', locals: { f: f } %>
        </div>
        <div class="card-footer">
          <%= button_tag('Download', type: 'submit', class: "btn btn-primary float-right") %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header with-border">
        <h3 class="card-title"><i class="fa fa-pie-chart fa-report report-icon"></i> <%= comments_report_name %></h3>
      </div>
      <%= simple_form_for :report, url: scorecard_comments_reports_path(format: :xlsx), role: 'form', html: { class: 'form-horizontal' } do |f| %>
      <div class="card-body">
        <p>This report shows the first time comments have been recorded across initiatives.</p>
        <%= render partial: 'scorecard_selector', locals: { f: f } %>
        <%= f.input :date, as: :string, input_html: { data: { behaviour: "datepicker" }, autocomplete: "off" } %>
        <%= f.input :status, collection: options_for_comment_statuses, include_blank: false  %>
      </div>
      <div class="card-footer">
        <%= button_tag('Download', type: 'submit', class: "btn btn-primary float-right") %>
      </div>
      <% end %>
    </div>
  </div>

  <%- if policy(:report).transition_card_activity? %>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header with-border">
          <h3 class="card-title"><i class="fa fa-pie-chart fa-report report-icon"></i> <%= activity_report_name %></h3>
        </div>
        <%= simple_form_for :report, url: transition_card_activity_reports_path(format: :xlsx), role: 'form', html: { class: 'form-horizontal' } do |f| %>
        <div class="card-body">
          <p>This report shows the addition and removal of characteristics across initiatives over a period of time.</p>

          <%= render partial: 'scorecard_selector', locals: { f: f } %>
          <%= f.input :date_from, :as => :string, :input_html => { data: { behaviour: "datepicker", datepicker_position: "bottom" }, autocomplete: "off" } %>
          <%= f.input :date_to, :as => :string, :input_html => { data: { behaviour: "datepicker" }, autocomplete: "off" } %>

        </div>
        <div class="card-footer">
          <%= button_tag('Download', type: 'submit', class: "btn btn-primary float-right") %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
<div>

app/views/reports/initiatives.html.erb
<div class="box">
  <div class='box-body no-padding'>
  <%= table_for @results, :table_html => { :class => "table table-striped" },
                        :sortable => true,
                        :data_row_html => {
                          id: lambda { |initiative| "initiative-#{initiative.id}" }
                        } do |table| %>
    <% table.column :name, link: true %>
    <% table.column :description, formatter: lambda { |description| Nokogiri::HTML(description).text} %>
    <% table.column :scorecard_name, :header => Scorecard.model_name.human %>
    <% table.column :wicked_problem_name, :header => "Wicked Problem"  %>
    <% table.column :community_name, :header => "Community"  %>
    <% table.column :created_at, :header => "Time" %>
    <% table.footer do %>
      <div class="float-right">
        <%= paginate @results %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/reports/scorecard_activity.html.erb
<div class="box">
  <div class='box-body no-padding'>
    <div class="box-header with-border">
      <div class="float-right">
        <%= link_to(scorecard_activity_reports_path(report: {scorecard_id: @scorecard.id, date_from: @date_from, date_to: @date_to}, format: :csv), 
          class: 'btn btn-primary') do
          safe_join([content_tag(:i, '', class: "fa fa-download"), ' Download'])
        end %>
      </div>
    
      <h3><%= Scorecard.model_name.human %>: <%= @report.scorecard.name %></h3>
      <h3>Date range: <%= @report.date_from.strftime('%d/%m/%y') %> to <%= @report.date_to.strftime('%d/%m/%y') %></h3>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>&nbsp;</th>  
          <th>Total Initiatives beginning of period</th>  
          <th>Additions</th>  
          <th>Removals</th>  
          <th>Total Initiatives end of period</th>  
        </tr>
      </thead>
      <tbody>
        
        <tr>
          <td><strong><%= Scorecard.model_name.human %> Initiatives</strong></td>
          <td><%= @report.initiative_totals[:initial] %></td>
          <td><%= @report.initiative_totals[:additions] %></td>
          <td><%= @report.initiative_totals[:removals] %></td>
          <td><%= @report.initiative_totals[:final] %></td>
        </tr>
        
        <% current_focus_area_group = '' %>
        <% current_focus_area = '' %>
        <% @report.results.each_with_index do |result, index| %>
        
        <% if result[:focus_area_group] != current_focus_area_group %>
          <% current_focus_area_group = result[:focus_area_group] %>
          <% current_focus_area = '' %>
          <tr>
            <td><strong><%= result[:focus_area_group] %></strong></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
        
        <% if result[:focus_area] != current_focus_area %>
          <% current_focus_area = result[:focus_area] %>
          <tr>
            <td style="text-align: right"><strong><%= result[:focus_area] %></strong></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
        
        <tr>
          <td style="text-align: right"><%= result[:characteristic] %></td>  
          <td><%= result[:initial] %></td>  
          <td><%= result[:additions] %></td>  
          <td><%= result[:removals] %></td>  
          <td><%= result[:final] %></td>  
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/scorecard_comments.html.erb
<div class="box">
  <div class='box-body no-padding'>
    <div class="box-header with-border">
      <div class="float-right">
        <%= link_to(scorecard_comments_reports_path(report: {scorecard_id: @scorecard.id, date: @date}, format: :csv), 
          class: 'btn btn-primary') do
          safe_join([content_tag(:i, '', class: "fa fa-download"), ' Download'])
        end %>
      </div>
    
      <h3><%= Scorecard.model_name.human %>: <%= @report.scorecard.name %></h3>
      <h3>Date: <%= @report.date.strftime('%d/%m/%y') %></h3>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>&nbsp;</th>  
          <th>Total initiatives</th>  
          <th>Total comments</th>  
          <% @report.initiatives.each_with_index do |_, index| %>
            <th><%= "Initiative #{index+1}"%></th>  
          <% end %>  
        </tr>
      </thead>
      <tbody>
        <% current_focus_area_group = '' %>
        <% current_focus_area = '' %>
        <% @report.results.each do |result| %>
        
        <% if result[:focus_area_group] != current_focus_area_group %>
          <% current_focus_area_group = result[:focus_area_group] %>
          <% current_focus_area = '' %>
          <tr>
            <td><strong><%= result[:focus_area_group] %></strong></td>
            <% (@report.initiatives.count + 2).times do %>
              <td></td>
            <% end %>  
          </tr>
        <% end %>
        
        <% if result[:focus_area] != current_focus_area %>
          <% current_focus_area = result[:focus_area] %>
          <tr>
            <td style="text-align: right"><strong><%= result[:focus_area] %></strong></td>
            <% (@report.initiatives.count + 2).times do %>
              <td></td>
            <% end %>  
          </tr>
        <% end %>
        <tr>
          <td style="text-align: right"><%= result[:characteristic] %></td>   
          <td><%= result[:initiatives_count] %></td>  
          <td><%= result[:comment_counts] %></td>  
          <% @report.initiatives.each_with_index do |_, index| %>
            <td><%= result["initiative_#{index+1}".to_sym] %></td>  
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/stakeholders.html.erb
<div class="box">
  <div class='box-body no-padding'>
  <%= table_for @results, :table_html => { :class => "table table-striped" },
                        :sortable => true,
                        :data_row_html => {
                          id: lambda { |initiative| "initiative-#{initiative.id}" }
                        } do |table| %>
    <% table.column :name, link: true %>
    <% table.column :description, formatter: lambda { |description| Nokogiri::HTML(description).text} %>
    <% table.column :stakeholder_type_name, header: "Stakeholder Type" %>
    <% table.column :scorecard_name, header: Scorecard.model_name.human %>
    <% table.column :wicked_problem_name, header: "Wicked Problem"  %>
    <% table.column :community_name, header: "Community"  %>
    <% table.column :created_at, header: "Time" %>
    <% table.footer do %>
      <div class="float-right">
        <%= paginate @results %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>